FROM rails:4.2.6

RUN mkdir -p /app
WORKDIR /app

COPY Gemfile /app
COPY Gemfile.lock /app
RUN bundle install --without test development

COPY . /app

ENV RAILS_ENV production
ENV RACK_ENV production
ENV SECRET_KEY_BASE 'assembly-secret'
RUN rake assets:precompile